### PR TITLE
Updated grammar + ping.js

### PR DESCRIPTION
**Pull request by LavishSphere**
Ping shows real ping and updated grammar.

### CODE REVIEW

**Comment by LavishSphere** [comment]
Bump

**Comment by AnushK-Fro** [comment]
Bump

**Comment by AnushK-Fro** [comment]
Bump

**Comment by AnushK-Fro** [comment]
Bump

**Comment by AnushK-Fro** [comment]
Bump

**Comment by AnushK-Fro** [comment]
Bump

**Comment by AnushK-Fro** [comment]
Bump

**Comment by AnushK-Fro** [comment]
Bump

**Comment by AnushK-Fro** [comment]
Bump

**Comment by AnushK-Fro** [comment]
Bump

**Comment by AnushK-Fro** [comment]
Bump

**Comment by AnushK-Fro** [comment]
Bump

**Comment by AnushK-Fro** [comment]
Bump

**Comment by AnushK-Fro** [comment]
Bump

**Comment by AnushK-Fro** [comment]
Bump

**Comment by AnushK-Fro** [comment]
Bump

**Comment by AnushK-Fro** [comment]
Bump

**Comment by AnushK-Fro** [comment]
Bump

**Comment by AnushK-Fro** [comment]
Bump

**Comment by AnushK-Fro** [comment]
Bump

**Comment by AnushK-Fro** [comment]
Bump

**Comment by AnushK-Fro** [comment]
Bump

**Comment by AnushK-Fro** [comment]
Bump

**Comment by AnushK-Fro** [comment]
Bump

**Comment by AnushK-Fro** [comment]
Bump

**Comment by AnushK-Fro** [comment]
Bump

**Comment by AnushK-Fro** [comment]
Bump

**Comment by AnushK-Fro** [comment]
Bump

**Comment by AnushK-Fro** [comment]
Bump

**Comment by AnushK-Fro** [comment]
Bump

**Comment by AnushK-Fro** [comment]
Bump

**Comment by AnushK-Fro** [comment]
Bump

**Comment by AnushK-Fro** [comment]
Bump

**Comment by AnushK-Fro** [comment]
Bump

**Comment by AnushK-Fro** [comment]
Bump

**Comment by AnushK-Fro** [comment]
Bump

**Comment by AnushK-Fro** [comment]
Bump

**Comment by AnushK-Fro** [comment]
Bump

**Comment by AnushK-Fro** [comment]
Bump

**Comment by AnushK-Fro** [comment]
Bump

**Comment by AnushK-Fro** [comment]
Bump

**Comment by AnushK-Fro** [comment]
Bump

**Comment by AnushK-Fro** [comment]
Bump

**Comment by AnushK-Fro** [comment]
Bump

**Comment by AnushK-Fro** [comment]
Bump

**Comment by AnushK-Fro** [comment]
Bump

**Comment by AnushK-Fro** [comment]
Bump

**Comment by AnushK-Fro** [comment]
Bump

**Comment by AnushK-Fro** [comment]
Bump

**Comment by AnushK-Fro** [comment]
Bump

**Comment by AnushK-Fro** [comment]
Bump

**Comment by AnushK-Fro** [comment]
Bump

**Comment by AnushK-Fro** [comment]
Bump

**Comment by AnushK-Fro** [comment]
Bump

**Comment by AnushK-Fro** [comment]
Bump

**Comment by AnushK-Fro** [comment]
Bump

**Comment by AnushK-Fro** [comment]
Bump

**Comment by AnushK-Fro** [comment]
Bump

**Comment by AnushK-Fro** [comment]
Bump

**Comment by AnushK-Fro** [comment]
Bump

**Comment by AnushK-Fro** [comment]
Bump

**Comment by AnushK-Fro** [comment]
Bump

**Comment by AnushK-Fro** [comment]
Bump

**Comment by AnushK-Fro** [comment]
Bump

**Comment by AnushK-Fro** [comment]
Bump

**Comment by AnushK-Fro** [comment]
Bump

**Comment by AnushK-Fro** [comment]
Bump

**Comment by AnushK-Fro** [comment]
Bump

**Comment by AnushK-Fro** [comment]
Bump

**Comment by AnushK-Fro** [comment]
Bump

**Comment by AnushK-Fro** [comment]
Bump

**Comment by AnushK-Fro** [comment]
Bump

**Comment by AnushK-Fro** [comment]
Bump

**Comment by AnushK-Fro** [comment]
Bump

**Comment by AnushK-Fro** [comment]
Bump

**Comment by AnushK-Fro** [comment]
Bump

**Comment by AnushK-Fro** [comment]
Bump

**Comment by AnushK-Fro** [comment]
Bump

**Comment by AnushK-Fro** [comment]
Bump

**Comment by AnushK-Fro** [comment]
Bump

**Comment by AnushK-Fro** [comment]
Bump

**Comment by AnushK-Fro** [comment]
bump

**Comment by AnushK-Fro** [comment]
Bump

**Comment by AnushK-Fro** [comment]
Today at 12:36 AM

**Comment by AnushK-Fro** [comment]
Bump

**Comment by LavishSphere** [comment]
bump

**Comment by LavishSphere** [comment]
bump

**Comment by LavishSphere** [comment]
bump

**Comment by OddDevelopment** [comment]
Bump ong

**Pull request closed without merging**
